### ISSUE TITLE
Error in Edge Detection

### ISSUE THREAD

**Issue by brainrichtech** [Rhathe/EdgeDetect#1]
Hai i am running your edge detection code in hadoop 1.2.1 with eclipse using lena images

i am got errors please help to solve the error

Exception in thread "main" java.lang.IllegalArgumentException: Wrong FS: file://localhost:8080/0, expected: file:///
    at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:390)
    at org.apache.hadoop.fs.RawLocalFileSystem.pathToFile(RawLocalFileSystem.java:55)
    at org.apache.hadoop.fs.LocalFileSystem.pathToFile(LocalFileSystem.java:61)
    at org.apache.hadoop.fs.LocalFileSystem.exists(LocalFileSystem.java:51)
    at EdgeDetect.main(EdgeDetect.java:96)

please urgent help me...

thanks 
by sakthi

**Comment by Rhathe** [comment]
Your hadoop config is probably not setup correctly.

http://techidiocy.com/java-lang-illegalargumentexception-wrong-fs-expected-file/

**Comment by Rhathe** [comment]
As there seems to be no reply to this I'm closing this issue.
